# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2dc86c70de29d2df8e23f0c4ccb543e4d6ca52a9a118691dc4ebd906b848e6e048a7b47cd568d4ad059f7f3209232a1ec2e603d71ce27fc51ac0ad345c4249d

test:
  secret_key_base: c3a24162fca710225677b59e57b0d74786b32dab2fb813e7b590a37cea64254a9e94ee51a20b8bb58c77b3bed7e014756c7920389126f0e5cd1ede30e0dd40e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
